name: Verify PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Pull Request Labels
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'deploy-dev'
          pull-request-number: '${{ github.event.pull_request.number }}'
