name: Verify PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Pull Request Labels
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "dev-deploy-ready"
