name: Verify PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Pull Request Labels
        uses: yogevbd/enforce-label-action@2.2.1
        with:
          REQUIRED_LABELS_ALL: "ready-for-dev"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Label required to merge: ready-for-dev"
